/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package screeny.client.gui;

import screeny.client.ScreenyClient;
import screeny.client.process.LoginDataCheckerStandalone;
import screeny.client.process.StartupProcess;

import javax.swing.*;
import java.awt.*;

public class LoginGui extends javax.swing.JFrame {

    /**
     * Creates new form StartupForm
     */
    private JFrame jFrame;
    // Variables declaration - do not modify
    private javax.swing.JButton jBLogin;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField jPFPassword;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTFServer;
    private javax.swing.JTextField jTFUsername;
    public LoginGui() {
        initComponents();
        jFrame = this;
        setTitle( "screeny.cc - Login" );
        setIconImage( new ImageIcon( LoginGui.class.getResource( "/icon_48x48.png" ) ).getImage() );
        setLocationRelativeTo( null );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTFUsername = new javax.swing.JTextField();
        jBLogin = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jPFPassword = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jTFServer = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation( javax.swing.WindowConstants.EXIT_ON_CLOSE );
        setCursor( new java.awt.Cursor( java.awt.Cursor.DEFAULT_CURSOR ) );
        setResizable( false );

        jLabel3.setFont( new java.awt.Font( "Tahoma", 1, 14 ) ); // NOI18N
        jLabel3.setText( "Username:" );

        jLabel4.setFont( new java.awt.Font( "Tahoma", 1, 14 ) ); // NOI18N
        jLabel4.setText( "Passwort:" );

        jTFUsername.addActionListener( new java.awt.event.ActionListener() {
            public void actionPerformed( java.awt.event.ActionEvent evt ) {
                jTFUsernameActionPerformed( evt );
            }
        } );


        jBLogin.setText( "Einloggen" );
        jBLogin.addActionListener( new java.awt.event.ActionListener() {
            public void actionPerformed( java.awt.event.ActionEvent evt ) {
                jBLoginActionPerformed( evt );
            }
        } );

        jCheckBox1.setText( "Autostart - Coming soon" );
        jCheckBox1.setEnabled( false );

        jLabel1.setFont( new java.awt.Font( "Tahoma", 1, 24 ) ); // NOI18N
        jLabel1.setText( "screeny.cc" );

        jLabel5.setFont( new java.awt.Font( "Tahoma", 1, 14 ) ); // NOI18N
        jLabel5.setText( "Server:" );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout( jPanel1 );
        jPanel1.setLayout( jPanel1Layout );
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING )
                        .addGroup( jPanel1Layout.createSequentialGroup()
                                .addGroup( jPanel1Layout.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING, false )
                                        .addGroup( jPanel1Layout.createSequentialGroup()
                                                .addGap( 114, 114, 114 )
                                                .addComponent( jLabel1 ) )
                                        .addGroup( jPanel1Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addGroup( jPanel1Layout.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING )
                                                        .addGroup( jPanel1Layout.createSequentialGroup()
                                                                .addGroup( jPanel1Layout.createParallelGroup( javax.swing.GroupLayout.Alignment.TRAILING )
                                                                        .addComponent( jLabel3 )
                                                                        .addComponent( jLabel5 )
                                                                        .addComponent( jLabel4 ) )
                                                                .addPreferredGap( javax.swing.LayoutStyle.ComponentPlacement.RELATED )
                                                                .addGroup( jPanel1Layout.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING, false )
                                                                        .addComponent( jTFUsername )
                                                                        .addComponent( jPFPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE )
                                                                        .addComponent( jTFServer ) ) )
                                                        .addGroup( jPanel1Layout.createSequentialGroup()
                                                                .addGap( 5, 5, 5 )
                                                                .addComponent( jCheckBox1 ) ) ) )
                                        .addGroup( jPanel1Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent( jBLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE ) ) )
                                .addContainerGap( javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE ) )
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING )
                        .addGroup( javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap( 6, 6, 6 )
                                .addComponent( jLabel1 )
                                .addPreferredGap( javax.swing.LayoutStyle.ComponentPlacement.UNRELATED )
                                .addGroup( jPanel1Layout.createParallelGroup( javax.swing.GroupLayout.Alignment.BASELINE )
                                        .addComponent( jLabel3 )
                                        .addComponent( jTFUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE ) )
                                .addPreferredGap( javax.swing.LayoutStyle.ComponentPlacement.RELATED )
                                .addGroup( jPanel1Layout.createParallelGroup( javax.swing.GroupLayout.Alignment.BASELINE )
                                        .addComponent( jPFPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE )
                                        .addComponent( jLabel4 ) )
                                .addPreferredGap( javax.swing.LayoutStyle.ComponentPlacement.RELATED )
                                .addGroup( jPanel1Layout.createParallelGroup( javax.swing.GroupLayout.Alignment.BASELINE )
                                        .addComponent( jLabel5 )
                                        .addComponent( jTFServer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE ) )
                                .addPreferredGap( javax.swing.LayoutStyle.ComponentPlacement.RELATED )
                                .addComponent( jCheckBox1 )
                                .addPreferredGap( javax.swing.LayoutStyle.ComponentPlacement.RELATED )
                                .addComponent( jBLogin )
                                .addContainerGap( javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE ) )
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout( getContentPane() );
        getContentPane().setLayout( layout );
        layout.setHorizontalGroup(
                layout.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING )
                        .addComponent( jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE )
        );
        layout.setVerticalGroup(
                layout.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING )
                        .addComponent( jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE )
        );

        pack();
    }// </editor-fold>

    private void jTFUsernameActionPerformed( java.awt.event.ActionEvent evt ) {
        // TODO add your handling code here:
    }

    private void jBLoginActionPerformed( java.awt.event.ActionEvent evt ) {
        jBLogin.setEnabled( false );
        ScreenyClient.getClientSettingsStore().setServerAddress( jTFServer.getText() );
        ScreenyClient.getExecutor().execute( new Runnable() {
            @Override
            public void run() {
                LoginDataCheckerStandalone loginDataCheckerStandalone = new LoginDataCheckerStandalone( "", jTFUsername.getText(), new String( jPFPassword.getPassword() ), new LoginDataCheckerStandalone.LoginDataCheckerResponse() {
                    @Override
                    public void success() {
                        // Continue startupProcess
                        StartupProcess.startupNormal();
                        SwingUtilities.invokeLater( new Runnable() {
                            @Override
                            public void run() {
                                jBLogin.setEnabled( true );
                                dispose();
                                StartupProcess.setLoginGui( null );
                            }
                        } );
                    }

                    @Override
                    public void exception( Throwable throwable ) {
                        SwingUtilities.invokeLater( new Runnable() {
                            @Override
                            public void run() {
                                JOptionPane.showMessageDialog( jFrame, "Fehler beim verbinden: " + throwable.getMessage(), "Fehler", JOptionPane.ERROR_MESSAGE );
                                jBLogin.setEnabled( true );
                            }
                        } );
                    }
                } );
                loginDataCheckerStandalone.check();
            }
        } );
    }

    public void start() {
        //</editor-fold>
        /* Create and display the form */
        EventQueue.invokeLater( new Runnable() {
            public void run() {
                jTFServer.setText( ScreenyClient.getClientSettingsStore().getServerAddress() );

                jTFUsername.setText( ScreenyClient.getClientSettingsStore().getUsername() );
                setVisible( true );
            }
        } );
    }
    // End of variables declaration
}
